### ISSUE TITLE
Create tweets independent from GWASbot

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/EnrichrBot#2]
We can have Enrichr tweet enrichment analysis results randomly selected from the GWAS Catalog, RNA-seq GEO signatures, and MGI 2019 lists.

**Comment by u8sand** [comment]
I just tried (with success) one of the ones that was in the uk bio bank. I'll set it up to run daily with those catalogs.

**Comment by AviMaayan** [comment]
The UK Biobank lists do not make much sense so I suggest not to use this file until we feel we got it right... For now, please use the new MGI library Alex created instead. Also, the tweet should include the source (library name) in addition to the description of the gene set (the gene set term).

**Comment by u8sand** [comment]
I did this in the second commit--any library in enrichr can be used. I did,
however, forget to put the library name, I'll do that.

**Comment by u8sand** [comment]
These changes have been applied, and the bots deployed.
