### ISSUE TITLE
Create 5 clear folders for each of the bot activities

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/EnrichrBot#6]
- Random Enrichr list
- Random IDG gene
- Reply to GWASbot
- Daily gene comment
- Weekly genes synopsis

**Comment by bartala** [comment]
Done.
Daily/Weekly tweets are in the same folder since they are invoked by the same script, as explained [here](https://drive.google.com/file/d/18EMNGMqNlsK3GcLuAMo1R-foKArV6VwP/view?usp=sharing).

**Comment by AviMaayan** [comment]
I do not see any of the requested changes.

**Comment by bartala** [comment]
Its under Maayanlab/EnrichrBot/enrichrbot/...
