### ISSUE TITLE
Asked EnrichrBot about this valid gene name C6ORF106 but EnrichrBot did not recognized it

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/EnrichrBot#9]

**Comment by bartala** [comment]
The gene synonym 'C6ORF106' is under gene symbol 'ILRUN' or 'LOC105369222'.
That's why EnrichrBot did not find it.
EnrichrBot will now search gene synonym and post a reply: 
"I'm confused. Did you mean <gene>?\nPlease reply: @BotEnrichr <gene symbol>.\nFor example: @BotEnrichr <gene>"
